import "./globals.css";

//Internal import

import Navbar from "./Components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com"></link> */}
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
